baseURL = 'https://www.adswashandseal.com/'
languageCode = 'en-us'
title = 'A.D.S. Wasing & Sealing'
[params]
  ShowVideo = true
  HeroVideo = '/videos/hero.mp4'
  HeroTitle = 'AWARD WINNING '
  HeroSubtitle = 'Washing & Sealing Services'
  HeroParagraph = 'A.D.S. offers applications for Concrete, Interlock, and Asphalt in the Greater Hamilton Area.'
  HeroButtonText = 'Free Estimate'
  HeroButtonLink = '/contact'

  [[params.reviews]]
    name = 'Shawn Rafacz'
    review = 'These guys are great...top shelf! We had brick relifting, resanding & Sealing done for both interlocking & agrigate and we absolutely love the job BJ & the ADS team did highly recommended 👍'
    link= 'https://maps.app.goo.gl/YhHXRgCwGUWpyUup6'
  [[params.reviews]]
    name = 'Greg Peachey'
    review = 'Contacted ADS Wash and Seal to do my a major job on interlocking brick for driveway, patio, walks and pool surround. On site visit to provide an estimate which was appropriate and competitive with other companies. Choose ADS based on their responsiveness to e mail. The team led by BJ did an excellent job resetting pavers, adjusting drain spots and replacing cracked stones as needed. Power washing, sanding and sealing followed. The whole job took about 2 weeks but was delayed by weather issues. Extremely pleased with the final result and the attention given to the final product. Excellent customer service and very responsive to ensure customer satisfaction. I will book this company to do work in the future and would highly recommend them.'
    link = 'https://maps.app.goo.gl/d6MyMt5DAPcJRthN9'

  [[params.reviews]]
    name = 'Mike S'
    review = 'We just got our driveway, steps and path washed and sealed. We couldn’t be happier with the whole process from start to finish. The end result is amazing! Would highly recommend them to anyone looking to bring their driveway back to its former glory.'
    link = 'https://maps.app.goo.gl/Hf9UqcYbREdm64UR7'

  [[params.reviews]]
    name = 'Lisa H'
    review = 'I highly recommend A.D.S. Washing and Sealing to everyone for many reasons!Their prices are more than fair. Communication prior to the job date was clear and helpful. They showed up when promised. Lorenzo was thorough and meticulous when applying the concrete sealer and he was a pleasure to have around! Funny, friendly and knowledgeable. 🙂 I am going to contact A.D.S to come back and seal my driveway as well as my parents in the near future. Don’t hesitate to call them, they are awesome!'
    link = 'https://maps.app.goo.gl/hjKEaqXuEuRdfjc39'

  [[params.clients]]
    name = 'Golfy Concrete & Drain LTD.'
    logo = '/images/clients/Golfi.png'

  [[params.clients]]
    name = 'Hamilton Builders Supply'
    logo = '/images/clients/hbs.png'

  [[params.clients]]
    name = 'Jet Black'
    logo = '/images/clients/JetBlack.png'

  [[params.clients]]
    name = 'LOSANI HOMES'
    logo = '/images/clients/LosaniHomes.png'

  [[params.clients]]
    name = 'Pro Pavement Services LTD'
    logo = '/images/clients/ProPavement.png'

  [services]
    [services.concrete]
      title = 'Concrete Wasing & Sealing'
      description = 'Clean, protect, and enhance your exterior surfaces with our comprehensive pressure washing and sealing.'
      image = '/images/concrete.jpg'
      link = '/services/concrete'
    [services.asphalt]
      title = 'Asphalt & Repair'
      description = 'Prevent costly damage, increase lifespan, enhances appearance an speed up ice and snow melt.'
      image = '/images/asphalt.jpg'
      link = '/services/asphalt'
    [services.interlock]
      title = 'Interlock Install & Restoration'
      description = 'From creating a new design to fixing existing issues like weed overgrowth and brick shifting.'
      image = '/images/interlock.jpg'
      link = '/services/interlock'
[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
