name: Deploy Hugo to Nginx

on:
  push:
    branches:
      - main  # Change to your default branch if different
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Get Hugo themes (true OR recursive)
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true  # If you need SCSS processing

      - name: Build
        run: hugo --minify

      - name: Backup existing deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            timestamp=$(date +%Y%m%d_%H%M%S)
            mkdir -p /var/www/backups
            if [ -d "/var/www/html" ]; then
              cp -r /var/www/html /var/www/backups/backup_$timestamp
              # Keep only last 5 backups
              ls -dt /var/www/backups/backup_* | tail -n +6 | xargs rm -rf
            fi

      - name: Deploy to temp directory
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          source: "public/*"
          target: "~/hugo-deploy-temp"
        strip_components: 1

      - name: Complete deployment with sudo script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            # Run our sudo-enabled deployment script
            sudo /usr/local/bin/hugo-deploy
